apiVersion: apps/v1
kind: Deployment
metadata:
  name: chinmayee-deployment-worker
  namespace: chinmayee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chinmayee-worker
  template:
    metadata:
      labels:
        app: chinmayee-worker
    spec:
      containers:
        - name: worker
          image: chinmayee606/worker:latest
          env:
            - name: DB_HOST
              value: "chinmayee-svc-postgres"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "postgres"
            - name: REDIS_HOST
              value: "chinmayee-svc-redis"